Level.ONE = new Level([
  'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'W                              W',
  'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'
]);
